### PR TITLE
Add docstrings and update documentation

### LINKED ISSUE #144: Make a real documentation
This has turned into a real library, but is lacking a real documentation. It should change to full docs because then they can be tested, unlike the README. Also then it could be populated using docstrings.

### LINKED ISSUE #181: What does "multi point derivatives" mean?
I'm not sure I understand what this function does: https://docs.sciml.ai/FiniteDiff/stable/#Multi-Point-Derivatives

### PR DESCRIPTION
**Pull request by gdalle**
Fix #144, fix #181

- Remove function signatures from `README.md` and add them as docstrings
- Structure all docstrings on the `docs/src/api.md` page
- Remove the additional comments from `README.md` and put them in the proper section of `docs/src/api.md` 
- Remove the tutorials from `README.md` and turn them into `docs/src/tutorials.md` (no doctests yet)
- Copy-paste both `README.md` and `docs/src/reproducibility.md` into `docs/src/index.md`

I didn't manage to update Documenter to v1.3 (it complained about the reproducibility part), so I'm leaving it for a later PR

### CODE REVIEW

**Comment by gdalle** [comment]
It looks like the downstream test fail on 1.6 has nothing to do with me? I didn't change the source code only the docstrings

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
Thanks!

> It looks like the downstream test fail on 1.6 has nothing to do with me? I didn't change the source code only the docstrings

We'll make this repo just follow the standard deprecation to LTS here.

**Comment by gdalle** [comment]
Is it expected that the new documentation doesn't show up on https://docs.sciml.ai/FiniteDiff/stable/ nor https://juliadiff.org/FiniteDiff.jl/stable/?
And which one of those is the right URL?

**Comment by ChrisRackauckas** [comment]
It needs to wait for the next global build

**Pull request merged**
