### PR TITLE
Add comparison to FiniteDifferences

### PR DESCRIPTION
**Pull request by oxinabox**
@ChrisRackauckas @wesselb do I have this right?
If once this is merges I will make the same PR to FiniteDifferences

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
yeah, that's about right. Though I would be weary of sending anyone the signal that FiniteDifferences.jl's higher order schemes are more accurate. That's not always the case, and it's definitely not the case with the default epsilons. Higher order finite difference schemes tend to turn into more of an intellectual curiosity when considering truncation error.

**Comment by oxinabox** [comment]
I think we ran into a case in the wild where we needed them.
I am not sure how to describe them.

**Comment by ChrisRackauckas** [comment]
I don't know if you needed them, as much as you needed a different choice of epsilon. In the lecture notes of https://mitmath.github.io/18337/lecture9/autodiff_dimensions 

image

I start off by showing that using a minimal epsilon is actually a really bad idea and will introduce more error than using a larger one.

image

FiniteDifferences.jl uses `eps(Float64) + TINY` which will make the floating point error larger than the actual truncation error. The optimal value to use is dependent on the differentiation method though, like second order central difference prefers `sqrt(eps(Float64))` and so on, so it's hard to have a good default in the FiniteDifferences.jl case...

**Comment by ChrisRackauckas** [comment]
Can always continue to improve.

**Comment by wesselb** [comment]
@ChrisRackauckas The `eps` in FiniteDifferences.jl is not the step size (epsilon) you're referring to. In FiniteDifferences.jl, the step size is automatically determined by balancing the truncation and round-off error. See Section 3 in some notes [here](https://www.dropbox.com/s/o62ar800feo2pr5/numerics.pdf?dl=1) for the precise expression that is used, if I didn't make a mistake. In particular, the resulting step size depends on a bound on the magnitude of a higher derivative, which (admittedly a bit crazy) is estimated by another, more robust finite-difference estimate. The point of this is to (1) actually get more accuracy out of higher-order methods by correctly estimating the step size and (2) have a robust procedure that is able to determine a near-optimal step sizes in many circumstances.

**Comment by oxinabox** [comment]
@wesselb  is this PR accurate? Should I make it on FiniteDifference.jl also?

**Comment by wesselb** [comment]
Yes, this seems about right to me. I do agree, though, with @ChrisRackauckas that we should be careful with claiming that higher-order methods necessarily yield more accuracy. (We could do a quick comparison to see whether this is the case or not.) Instead, maybe it can say that FiniteDifferences.jl can automatically determine good step sizes, which (in our experience so far) makes it robust and accurate in many cases without the need for hand tuning.

**Pull request merged**
